name: dockerize-on-mtrain

on: 
  push:
    paths:
      - mtrain/**
jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ssuwani
          password: <password>
      - name: Docker build
      - name: Docker push
