name: dockerize-on-mtrain

on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: tmsk0711
          password: <password>
      - name: Docker build
      - name: Docker push
