name: echo-hello # Workflow name

on: push # Trigger on push

jobs:
  echo-hello: # Job name
    runs-on: ubuntu-latest # Runner Selection 
    steps:
      - name: hello world with echo # step 1
        run: echo Hello World!

      - name: hello world with cli # step 2
        run: python -c "print('Hello World!')"

      - name: python version check
        run: python --version
